spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: company-service
        uri: lb://company-service
        predicates:
        - Path=/companies/**
      - id: car-service
        uri: lb://car-service
        predicates:
        - Path=/cars/**