spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: company-service
        uri: lb://company-service
        predicates:
        - Path=/companies/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: car-service
        uri: lb://car-service
        predicates:
        - Path=/cars/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *