spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: company
        uri: http://company:8080
        predicates:
        - Path=/companies/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: car
        uri: lb://car
        predicates:
        - Path=/cars/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *